[package]
name = "misonomi-hp"
version = "0.1.0"
authors = ["misonomi <misonomi0612@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
yew = "0.17.2"
web-sys = { version = "0.3.39", features = ["Window"] }

[features]
index = []
an-recruiter = []
kisekae = []
accessories = []
assemble = []
