
name: hp-deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Restore Cache
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: cargo-${{ hashFiles(Cargo.toml) }}
        restore-keys: |
          cargo-

    - name: Install cargo-web
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-web

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: web
        args: deploy

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        PERSONAL_TOKEN: ${{ secrets.TOKEN_REPO }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./target/deploy