
name: hp-deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Restore Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          cargo-

    - name: Install wasm-pack
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: wasm-pack

    - name: Build
      run: |
        wasm-pack build --target web --out-name index --out-dir ./static/index -- --features index

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        PERSONAL_TOKEN: ${{ secrets.TOKEN_REPO }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./static